### ISSUE TITLE
 Add seletion of "wertetyp", e.g. QUARTER_HOUR

### ISSUE THREAD

**Issue by gf78** [vrilcode/node-red-wnsm-b2b#2]
Thanks for your effort! I implemented something similar (https://github.com/gf78/smartmetervienna) but considering switching to node-red.

It would be cool, if you can add a node parmeter for the query param `wertetyp` with the following values:
* `DAY`
* `QUARTER_HOUR`
* `METER_READ`

Thank you!

**Comment by gf78** [comment]
added a pull request

**Comment by vrilcode** [comment]
Thanks for contribution! I've integrated your additions with some changes in v1.1.0. 

Your project looks great. I didn't notice, that there is already a Javascript implementation. Node-RED is awesome and an exceptionally well thought out piece of software.
