### ISSUE TITLE
Receiving error message with option "Yesterday"

### ISSUE THREAD

**Issue by 4immerjung** [vrilcode/node-red-wnsm-b2b#4]
Hi vrilcode,

Thank you very much for this node and your efforts.
I have had a smart meter from Wiener Netze for 3 days.
The "Yesterday" option does not work for me in the node settings. I get the error:
**"AxiosError: Request failed with status code 400"**
Last three days and current month are working fine.
Can you please take a look at this?

<img width="375" alt="node-red" src="https://github.com/vrilcode/node-red-wnsm-b2b/assets/60366145/ce1d06e6-81cc-4e56-bb1e-e208e584d2fe">

Thank you very much
4immerjung

**Comment by vrilcode** [comment]
Thanks for reporting. Should be fixed with current version 1.2.0.
